---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KeyName:
    Description: Existing EC2 KeyPair for SSH access.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: cfn-kubernetes

  DomainName:
    Type: String

  KubeVersion:
    Type: String

  Taints:
    Description: Taints to apply to worker node.
    Type: String
    Default: ""

  FeatureGates:
    Description: Feature Gates for kubelet
    Type: String
    Default: ""

  CPUManagerPolicy:
    Description: cpu manager policy for kubelet
    Type: String
    Default: "none"

  WorkerInstanceType:
    Description: EC2 instance type for controller nodes.
    Type: String

  WorkerPoolSizeMin:
    Description: Number of Worker Nodes
    Type: Number
    Default: 2

  WorkerPoolSizeMax:
    Description: Number of Worker Nodes
    Type: Number
    Default: 25

  WorkerVolumeSize:
    Description: Worker volume size in GB
    Type: Number
    Default: 100

  VPCID:
    Description: Existing VPC with attached internet gateway to use for this cluster.
    Type: AWS::EC2::VPC::Id

  PrivateSubnet:
    Type: String

  DockerOpts:
    Type: String
    Default: "--max-concurrent-downloads=15"

  InstanceRoleName:
    Type: String

  SecurityGroup:
    Type: String

  assetBucket:
    Type: String

Mappings:
  Assets:
    kubelet:
      unit: |
        [Unit]
        Description=Kubernetes Kubelet Server
        Documentation=https://github.com/kubernetes/kubernetes
        Requires=coreos-metadata.service
        After=coreos-metadata.service

        [Service]
        EnvironmentFile=/run/metadata/coreos
        EnvironmentFile=/etc/kubernetes.env
        Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
          --volume dns,kind=host,source=/etc/resolv.conf \
          --volume cni-opt,kind=host,source=/opt/cni \
          --volume cni-etc,kind=host,source=/etc/cni \
          --mount volume=dns,target=/etc/resolv.conf \
          --mount volume=cni-opt,target=/opt/cni \
          --mount volume=cni-etc,target=/etc/cni"
        ExecStartPre=/bin/mkdir -p /opt/cni /etc/cni /etc/kubernetes/manifests
        ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/run/kubelet-pod.uui
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --kubeconfig=/etc/kubernetes/admin.conf \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --cloud-provider=aws \
          --cloud-config=/etc/kubernetes/cloud-config \
          --network-plugin=cni \
          --pod-cidr=10.244.0.0/16 \
          --cluster-dns=10.96.0.10 \
          --node-ip=${COREOS_EC2_IPV4_LOCAL} \
          --cluster-domain=${KUBELET_CLUSTER_DOMAIN} \
          --register-with-taints=${KUBELET_TAINTS} \
          --feature-gates=${KUBELET_FEATURE_GATES} \
          --cpu-manager-policy=${KUBELET_CPU_MANAGER_POLICY} \
          --kube-reserved=cpu=100m \
          --system-reserved=cpu=100m \
          --allow-privileged
        ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
        [Install]
        WantedBy=multi-user.target

  # Generate with:
  # curl -L https://coreos.com/dist/aws/aws-stable.json \
  #   | jq 'to_entries|map(select(.key != "release_info"))|from_entries' \
  #   | json2yaml | sed 's/^/    /'
  RegionToImageMap:
    ap-northeast-1:
      hvm: ami-0b53d79c2d092ce77
      pv: ami-07bac8d675b35e587
    ap-northeast-2:
      hvm: ami-0a07af788e926e417
      pv: ''
    ap-south-1:
      hvm: ami-06103b4b4747ad077
      pv: ''
    ap-southeast-1:
      hvm: ami-0b0cfecc8175d06c6
      pv: ami-02c7f68bd43bb3cef
    ap-southeast-2:
      hvm: ami-03ec12353f77620c4
      pv: ami-0dbc10b5920f7e072
    ca-central-1:
      hvm: ami-07ec21c807d0c5176
      pv: ''
    cn-north-1:
      hvm: ami-054d6909d91900dcf
      pv: ami-02959c79557941cc1
    cn-northwest-1:
      hvm: ami-0bf16b12c53c5e9a3
      pv: ''
    eu-central-1:
      hvm: ami-0cfe08bc0484060f5
      pv: ami-02d1a2f9c9d3bfae5
    eu-west-1:
      hvm: ami-081f4de2b0f6032c6
      pv: ami-025424961938fb048
    eu-west-2:
      hvm: ami-0a937eebe9caafbb1
      pv: ''
    eu-west-3:
      hvm: ami-0bf3ed517b76f5c0d
      pv: ''
    sa-east-1:
      hvm: ami-09359810f00df88f2
      pv: ami-0d1e38ba1866b81f4
    us-east-1:
      hvm: ami-0547d9705af5e8fb2
      pv: ami-04cd3bf19e1cb48ed
    us-east-2:
      hvm: ami-08cb94999d76c8e42
      pv: ''
    us-gov-west-1:
      hvm: ami-00c3a061
      pv: ami-ecc1a28d
    us-west-1:
      hvm: ami-0b349483829492b39
      pv: ami-0944222061c50230a
    us-west-2:
      hvm: ami-0c1cc1260c7828fcb
      pv: ami-0c32a360898f214ca

Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRoleName

  WorkerLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap [ RegionToImageMap, !Ref "AWS::Region", hvm ]
      InstanceType: !Ref WorkerInstanceType
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeSize:
              Ref: WorkerVolumeSize
      IamInstanceProfile: !GetAtt [ InstanceProfile, Arn ]
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              {
                "ignition": {
                  "version": "2.1.0",
                  "config": {}
                },
                "storage": {
                  "files": [{
                      "filesystem": "root",
                      "path": "/etc/kubernetes/cloud-config",
                      "mode": 420,
                      "contents": { "source": "data:;base64,${cloudProviderConfig}" }
                    }, {
                      "filesystem": "root",
                      "path": "/etc/kubernetes/admin.conf",
                      "mode": 384,
                      "contents": { "source": "s3://${assetBucket}/${domain}/kubeadm/admin.conf" }
                    }, {
                      "filesystem": "root",
                      "path": "/etc/kubernetes.env",
                      "mode": 420,
                      "contents": { "source": "data:;base64,${kubernetesEnv}" }
                    }, {
                      "filesystem": "root",
                      "path": "/opt/bin/cfn-signal-success",
                      "mode": 493,
                      "contents": { "source": "data:;base64,${cfnSignalSuccess}" }
                    }
                  ]
                },
                "systemd": {
                  "units": [{
                    "name": "kubelet.service",
                    "enable": true,
                    "contents": "${kubeletUnit}"
                  }, {
                    "name": "update-engine.service",
                    "mask": true
                  }, {
                    "name": "locksmithd.service",
                    "mask": true
                  }, {
                    "name": "docker.service",
                    "enable": true,
                    "dropins": [{
                      "name": "20-docker-opts.conf",
                      "contents": "[Service]\nEnvironment=\"DOCKER_OPTS=${DockerOpts}\""
                    }]
                  }]
                },
                "networkd": {},
                "passwd": {}
              }
            - kubeletUnit: !Join
              - "\\n"
              - !Split
                - "\n"
                - !Join
                  - "\\\""
                  - !Split
                    - "\""
                    - !Join
                      - "\\\\"
                      - !Split
                        - "\\"
                        - !FindInMap [ Assets, kubelet, unit ]

              # Environment files
              kubernetesEnv:
                Fn::Base64:
                  Fn::Sub:
                    - |
                      KUBELET_IMAGE_URL=docker://gcr.io/google-containers/hyperkube-amd64
                      KUBELET_IMAGE_TAG=${KubeVersion}
                      KUBELET_CLUSTER_DOMAIN=${DomainName}
                      KUBELET_TAINTS=${Taints}
                      KUBELET_FEATURE_GATES=${FeatureGates}
                      KUBELET_CPU_MANAGER_POLICY=${CPUManagerPolicy}
                      RKT_GLOBAL_ARGS="--insecure-options=image"
                    - KubeVersion: !Ref KubeVersion
                      DomainName: !Ref DomainName
                      Taints: !Ref Taints
                      FeatureGates: !Ref FeatureGates
                      CPUManagerPolicy: !Ref CPUManagerPolicy
              cloudProviderConfig:
                Fn::Base64:
                  Fn::Sub:
                    - |
                      [Global]
                      KubernetesClusterTag=${DomainName}
                      KubernetesClusterID=${DomainName}
                    - DomainName: !Ref DomainName
              cfnSignalSuccess:
                Fn::Base64: !Sub
                  - |
                    #!/bin/bash
                    set -euo pipefail
                    echo "Signaling success"
                    docker run --rm rochacon/cfn-bootstrap cfn-signal \
                      --resource $1 \
                      --stack ${StackName} \
                      --region ${Region} || true # Ignore if signaling failed
                  - StackName: !Ref AWS::StackName
                    Region: !Ref AWS::Region
              domain: !Ref DomainName

  WorkerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet
      LaunchConfigurationName:
        Ref: WorkerLaunchConfiguration
      MaxSize: !Ref WorkerPoolSizeMax
      MinSize: !Ref WorkerPoolSizeMin
      Tags:
      - Key: StackName
        PropagateAtLaunch: true
        Value: !Ref AWS::StackName
      - Key: KubernetesCluster
        PropagateAtLaunch: true
        Value: !Ref DomainName
        # FIXME: We should check that cluster is healthy and signal success
        #    UpdatePolicy:
        #      AutoScalingRollingUpdate:
        #        MaxBatchSize: 1
        #        MinInstancesInService: 1
        #        PauseTime: PT15M
        #        WaitOnResourceSignals: true
